/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudiante;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 10
 */
public class FrameEstudiante extends javax.swing.JFrame {

    ArrayList<Estudiante> listaEstudiante = new ArrayList<Estudiante>();

    /**
     * Creates new form FrameEstudiante
     */
    public FrameEstudiante() {
        initComponents();
        setLocationRelativeTo(null);
        jtxtAreaMostrar.setEditable(false);
        setTitle("Datos Estudiante");
        jPanel1.setFocusable(true);

    }

    private void limpiarCampos() {
        this.jtxtCarnet.setText("");
        this.jtxtNombre.setText("");
        this.jtxtApellido.setText("");
        this.jtxtCarrera.setText("");
        this.jtxtNivel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtApellido = new javax.swing.JTextField();
        jtxtCarrera = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtNivel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtCarnet = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaMostrar = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnVerEstudiante = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Datos Estudiante");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 220, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Apellido :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, 20));

        jtxtApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtApellido.setForeground(new java.awt.Color(153, 153, 153));
        jtxtApellido.setText("Escribe tus apellidos...");
        jtxtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtApellidoFocusLost(evt);
            }
        });
        jPanel1.add(jtxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 640, 30));

        jtxtCarrera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtCarrera.setForeground(new java.awt.Color(153, 153, 153));
        jtxtCarrera.setText("Escribe tu carrera...");
        jtxtCarrera.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtCarreraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCarreraFocusLost(evt);
            }
        });
        jPanel1.add(jtxtCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 640, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Carrera :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 20));

        jtxtNivel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtNivel.setForeground(new java.awt.Color(153, 153, 153));
        jtxtNivel.setText("Escribe tu nivel...");
        jtxtNivel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtNivelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtNivelFocusLost(evt);
            }
        });
        jPanel1.add(jtxtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 640, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Nivel :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 70, 20));

        jtxtCarnet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtCarnet.setForeground(new java.awt.Color(153, 153, 153));
        jtxtCarnet.setText("Escribe tu carnet...");
        jtxtCarnet.setToolTipText("");
        jtxtCarnet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtCarnetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCarnetFocusLost(evt);
            }
        });
        jPanel1.add(jtxtCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 640, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Carnet :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 80, 20));

        jtxtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtNombre.setForeground(new java.awt.Color(153, 153, 153));
        jtxtNombre.setText("Escribe tus nombres...");
        jtxtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtNombreFocusLost(evt);
            }
        });
        jPanel1.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 640, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Nombre :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 90, 20));

        jtxtAreaMostrar.setColumns(20);
        jtxtAreaMostrar.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaMostrar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 740, 110));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 255), null, null));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 100, 40));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 255), null, null));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 100, 40));

        btnVerEstudiante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVerEstudiante.setForeground(new java.awt.Color(0, 0, 255));
        btnVerEstudiante.setText("Ver Estudiante");
        btnVerEstudiante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 255), null, null));
        btnVerEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstudianteActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 130, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 290, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String carneT = this.jtxtCarnet.getText();
        String nombrE = this.jtxtNombre.getText();
        String apellidO = this.jtxtApellido.getText();
        String carrerA = this.jtxtCarrera.getText();
        String niveL = this.jtxtNivel.getText();
        try {
            double car = Double.parseDouble(carneT);
            Estudiante estudiante = new Estudiante(car, nombrE, apellidO, carrerA, niveL);
            this.listaEstudiante.add(estudiante);
            this.limpiarCampos();
            JOptionPane.showMessageDialog(null, "Datos agregados correcatemente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lo datos no se han agregado", "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Este metodo esta aqui porque necesito limpiar los campos de los JTextField.
        this.limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVerEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstudianteActionPerformed
        // TODO add your handling code here:
        String lE = "";
        for (Estudiante es : listaEstudiante) {
            lE += es.getNombre() + " " + es.getApellido() + "\n";
        }
        this.jtxtAreaMostrar.setText(lE);
    }//GEN-LAST:event_btnVerEstudianteActionPerformed

    private void jtxtCarnetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCarnetFocusGained
        // TODO add your handling code here:
        if (jtxtCarnet.getText().trim().equals("Escribe tu carnet...")) {
            jtxtCarnet.setText("");
            jtxtCarnet.setForeground(new Color(153,153,153));
        }
        jtxtCarnet.setForeground(new Color(0, 0, 0));
        
    }//GEN-LAST:event_jtxtCarnetFocusGained

    private void jtxtCarnetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCarnetFocusLost
        // TODO add your handling code here:
        if (jtxtCarnet.getText().trim().equals("")) {
            jtxtCarnet.setText("Escribe tu carnet...");
        }
        jtxtCarnet.setForeground(new Color(153, 153, 153));
        
    }//GEN-LAST:event_jtxtCarnetFocusLost

    private void jtxtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtNombreFocusGained
        // TODO add your handling code here:
        if (jtxtNombre.getText().trim().equals("Escribe tus nombres...")) {
            jtxtNombre.setText("");
        }
        jtxtNombre.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jtxtNombreFocusGained

    private void jtxtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtNombreFocusLost
        // TODO add your handling code here:
        if (jtxtNombre.getText().trim().equals("")) {
            jtxtNombre.setText("Escribe tus nombres...");
        }
        jtxtNombre.setForeground(new Color(153, 153, 153));

    }//GEN-LAST:event_jtxtNombreFocusLost

    private void jtxtApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtApellidoFocusGained
        // TODO add your handling code here:
        if (jtxtApellido.getText().trim().equals("Escribe tus apellidos...")) {
            jtxtApellido.setText("");
        }
        jtxtApellido.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jtxtApellidoFocusGained

    private void jtxtApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtApellidoFocusLost
        // TODO add your handling code here:
        if (jtxtApellido.getText().trim().equals("")) {
            jtxtApellido.setText("Escribe tus apellidos...");
        }
        jtxtApellido.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jtxtApellidoFocusLost

    private void jtxtCarreraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCarreraFocusGained
        // TODO add your handling code here:
        if (jtxtCarrera.getText().trim().equals("Escribe tu carrera...")) {
            jtxtCarrera.setText("");
        }
        jtxtCarrera.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jtxtCarreraFocusGained

    private void jtxtCarreraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCarreraFocusLost
        // TODO add your handling code here:
        if (jtxtCarrera.getText().trim().equals("")) {
            jtxtCarrera.setText("Escribe tu carrera...");
        }
        jtxtCarrera.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jtxtCarreraFocusLost

    private void jtxtNivelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtNivelFocusGained
        // TODO add your handling code here:
        if (jtxtNivel.getText().trim().equals("Escribe tu nivel...")) {
            jtxtNivel.setText("");
        }
        jtxtNivel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jtxtNivelFocusGained

    private void jtxtNivelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtNivelFocusLost
        // TODO add your handling code here:
        if (jtxtNivel.getText().trim().equals("")) {
            jtxtNivel.setText("Escribe tu nivel...");
        }
        jtxtNivel.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jtxtNivelFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVerEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jtxtApellido;
    private javax.swing.JTextArea jtxtAreaMostrar;
    private javax.swing.JTextField jtxtCarnet;
    private javax.swing.JTextField jtxtCarrera;
    private javax.swing.JTextField jtxtNivel;
    private javax.swing.JTextField jtxtNombre;
    // End of variables declaration//GEN-END:variables
}
